# Cleaning and Exploring the Demographics and Programs data

In [49]:
import pandas as pd
import numpy as np
import openpyxl

In [67]:
df = pd.read_excel('All demographics and programs.xlsx')

In [ ]:
# drop the first name and last name columns since they don't have any names
# drop single parent because it is empty (only 1 row has 'No')
# drop Ethnicity Hispanic/Latino because it is all null
# drop Ex-Offender because only 1 row has No and the rest are null
# combined Transgender M to F and F to M to the category 'Transgender' because there were only 
# 16 that identifed M to F or F to M


def data_cleaning(df_clean):
    df_clean = df.drop(columns=['First Name','Last Name','Ethnicity Hispanic/Latino',
                     'Single Parent','Ex-Offender','Program: Program Name'])
    df_clean = df_clean['Gender'].str.replace('Transgender female to male','Transgender')
    df_clean = df_clean['Gender'].str.replace('Transgender male to female','Transgender')
    splitting = df_clean['Race'].str.split(';', expand=True)
    splitting.columns = [f'Race_{i+1}' for i in range(splitting.shape[1])]
    df_clean = pd.concat([df_clean, splitting], axis=1)
    df_clean.drop(columns=['Race'])
    return(df_clean)

df_clean

,Auto Id,Gender,Outcome,Veteran,Justice Involved,Race_1,Race_2,Race_3,Race_4
0,202107-1206,Male,NaN,No,NaN,Black or African American,None,None,None
1,202107-1206,Male,NaN,No,NaN,Black or African American,None,None,None
2,202107-1206,Male,NaN,No,NaN,Black or African American,None,None,None
3,202108-5167,Male,Successfully Completed,No,No,Asian,None,None,None
4,202108-5171,Male,NaN,NaN,NaN,Black or African American,None,None,None
...,...,...,...,...,...,...,...,...,...
32225,202502-20671,Female,NaN,NaN,NaN,White,None,None,None
32226,202410-17602,Female,NaN,NaN,NaN,White,None,None,None
32227,202506-23809,Female,NaN,NaN,NaN,White,None,None,None
32228,202410-17749,Female,NaN,NaN,NaN,White,None,None,None
32229,202505-23270,Male,NaN,NaN,NaN,White,None,None,None

In [70]:
# what does 'not applicable' mean for Veteran column
# what does Justice Involved column mean?
df_clean['Auto Id'].value_counts()

Auto Id
202210-9836     69
202302-10868    51
202206-8677     47
202501-19937    46
202110-5548     40
                ..
202211-10136     1
202210-9854      1
202210-9659      1
202210-9906      1
202208-9170      1
Name: count, Length: 9208, dtype: int64